export const COUNTRIES = [
    { code: '🇦🇫', label: 'Afghanistan' },
    { code: '🇦🇱', label: 'Albania' },
    { code: '🇩🇿', label: 'Algeria' },
    { code: '🇦🇷', label: 'Argentina' },
    { code: '🇦🇲', label: 'Armenia' },
    { code: '🇦🇺', label: 'Australia' },
    { code: '🇦🇹', label: 'Austria' },
    { code: '🇦🇿', label: 'Azerbaijan' },
    { code: '🇧🇭', label: 'Bahrain' },
    { code: '🇧🇩', label: 'Bangladesh' },
    { code: '🇧🇾', label: 'Belarus' },
    { code: '🇧🇪', label: 'Belgium' },
    { code: '🇧🇿', label: 'Belize' },
    { code: '🇧🇯', label: 'Benin' },
    { code: '🇧🇹', label: 'Bhutan' },
    { code: '🇧🇴', label: 'Bolivia' },
    { code: '🇧🇦', label: 'Bosnia and Herzegovina' },
    { code: '🇧🇼', label: 'Botswana' },
    { code: '🇧🇷', label: 'Brazil' },
    { code: '🇧🇬', label: 'Bulgaria' },
    { code: '🇧🇫', label: 'Burkina Faso' },
    { code: '🇧🇮', label: 'Burundi' },
    { code: '🇰🇭', label: 'Cambodia' },
    { code: '🇨🇲', label: 'Cameroon' },
    { code: '🇨🇦', label: 'Canada' },
    { code: '🇨🇻', label: 'Cape Verde' },
    { code: '🇨🇫', label: 'Central African Republic' },
    { code: '🇹🇩', label: 'Chad' },
    { code: '🇨🇱', label: 'Chile' },
    { code: '🇨🇳', label: 'China' },
    { code: '🇨🇴', label: 'Colombia' },
    { code: '🇰🇲', label: 'Comoros' },
    { code: '🇨🇬', label: 'Congo' },
    { code: '🇨🇩', label: 'Congo (DRC)' },
    { code: '🇨🇷', label: 'Costa Rica' },
    { code: '🇭🇷', label: 'Croatia' },
    { code: '🇨🇺', label: 'Cuba' },
    { code: '🇨🇾', label: 'Cyprus' },
    { code: '🇨🇿', label: 'Czech Republic' },
    { code: '🇩🇰', label: 'Denmark' },
    { code: '🇩🇯', label: 'Djibouti' },
    { code: '🇩🇴', label: 'Dominican Republic' },
    { code: '🇪🇨', label: 'Ecuador' },
    { code: '🇪🇬', label: 'Egypt' },
    { code: '🇸🇻', label: 'El Salvador' },
    { code: '🇪🇪', label: 'Estonia' },
    { code: '🇪🇹', label: 'Ethiopia' },
    { code: '🇫🇯', label: 'Fiji' },
    { code: '🇫🇮', label: 'Finland' },
    { code: '🇫🇷', label: 'France' },
    { code: '🇬🇪', label: 'Georgia' },
    { code: '🇩🇪', label: 'Germany' },
    { code: '🇬🇭', label: 'Ghana' },
    { code: '🇬🇷', label: 'Greece' },
    { code: '🇬🇹', label: 'Guatemala' },
    { code: '🇬🇳', label: 'Guinea' },
    { code: '🇭🇹', label: 'Haiti' },
    { code: '🇭🇳', label: 'Honduras' },
    { code: '🇭🇰', label: 'Hong Kong' },
    { code: '🇭🇺', label: 'Hungary' },
    { code: '🇮🇸', label: 'Iceland' },
    { code: '🇮🇳', label: 'India' },
    { code: '🇮🇩', label: 'Indonesia' },
    { code: '🇮🇷', label: 'Iran' },
    { code: '🇮🇶', label: 'Iraq' },
    { code: '🇮🇪', label: 'Ireland' },
    { code: '🇮🇱', label: 'Israel' },
    { code: '🇮🇹', label: 'Italy' },
    { code: '🇯🇲', label: 'Jamaica' },
    { code: '🇯🇵', label: 'Japan' },
    { code: '🇯🇴', label: 'Jordan' },
    { code: '🇰🇿', label: 'Kazakhstan' },
    { code: '🇰🇪', label: 'Kenya' },
    { code: '🇰🇼', label: 'Kuwait' },
    { code: '🇰🇬', label: 'Kyrgyzstan' },
    { code: '🇱🇦', label: 'Laos' },
    { code: '🇱🇻', label: 'Latvia' },
    { code: '🇱🇧', label: 'Lebanon' },
    { code: '🇱🇾', label: 'Libya' },
    { code: '🇱🇮', label: 'Liechtenstein' },
    { code: '🇱🇹', label: 'Lithuania' },
    { code: '🇱🇺', label: 'Luxembourg' },
    { code: '🇲🇴', label: 'Macau' },
    { code: '🇲🇰', label: 'Macedonia' },
    { code: '🇲🇬', label: 'Madagascar' },
    { code: '🇲🇾', label: 'Malaysia' },
    { code: '🇲🇻', label: 'Maldives' },
    { code: '🇲🇱', label: 'Mali' },
    { code: '🇲🇹', label: 'Malta' },
    { code: '🇲🇽', label: 'Mexico' },
    { code: '🇲🇩', label: 'Moldova' },
    { code: '🇲🇨', label: 'Monaco' },
    { code: '🇲🇳', label: 'Mongolia' },
    { code: '🇲🇪', label: 'Montenegro' },
    { code: '🇲🇦', label: 'Morocco' },
    { code: '🇲🇿', label: 'Mozambique' },
    { code: '🇲🇲', label: 'Myanmar' },
    { code: '🇳🇦', label: 'Namibia' },
    { code: '🇳🇵', label: 'Nepal' },
    { code: '🇳🇱', label: 'Netherlands' },
    { code: '🇳🇿', label: 'New Zealand' },
    { code: '🇳🇮', label: 'Nicaragua' },
    { code: '🇳🇪', label: 'Niger' },
    { code: '🇳🇬', label: 'Nigeria' },
    { code: '🇰🇵', label: 'North Korea' },
    { code: '🇳🇴', label: 'Norway' },
    { code: '🇴🇲', label: 'Oman' },
    { code: '🇵🇰', label: 'Pakistan' },
    { code: '🇵🇸', label: 'Palestine' },
    { code: '🇵🇦', label: 'Panama' },
    { code: '🇵🇾', label: 'Paraguay' },
    { code: '🇵🇪', label: 'Peru' },
    { code: '🇵🇭', label: 'Philippines' },
    { code: '🇵🇱', label: 'Poland' },
    { code: '🇵🇹', label: 'Portugal' },
    { code: '🇶🇦', label: 'Qatar' },
    { code: '🇷🇴', label: 'Romania' },
    { code: '🇷🇺', label: 'Russia' },
    { code: '🇷🇼', label: 'Rwanda' },
    { code: '🇸🇦', label: 'Saudi Arabia' },
    { code: '🇸🇳', label: 'Senegal' },
    { code: '🇷🇸', label: 'Serbia' },
    { code: '🇸🇬', label: 'Singapore' },
    { code: '🇸🇰', label: 'Slovakia' },
    { code: '🇸🇮', label: 'Slovenia' },
    { code: '🇸🇴', label: 'Somalia' },
    { code: '🇿🇦', label: 'South Africa' },
    { code: '🇰🇷', label: 'South Korea' },
    { code: '🇪🇸', label: 'Spain' },
    { code: '🇱🇰', label: 'Sri Lanka' },
    { code: '🇸🇩', label: 'Sudan' },
    { code: '🇸🇪', label: 'Sweden' },
    { code: '🇨🇭', label: 'Switzerland' },
    { code: '🇸🇾', label: 'Syria' },
    { code: '🇹🇼', label: 'Taiwan' },
    { code: '🇹🇯', label: 'Tajikistan' },
    { code: '🇹🇿', label: 'Tanzania' },
    { code: '🇹🇭', label: 'Thailand' },
    { code: '🇹🇱', label: 'Timor-Leste' },
    { code: '🇹🇬', label: 'Togo' },
    { code: '🇹🇳', label: 'Tunisia' },
    { code: '🇹🇷', label: 'Turkey' },
    { code: '🇹🇲', label: 'Turkmenistan' },
    { code: '🇺🇬', label: 'Uganda' },
    { code: '🇺🇦', label: 'Ukraine' },
    { code: '🇦🇪', label: 'United Arab Emirates' },
    { code: '🇬🇧', label: 'United Kingdom' },
    { code: '🇺🇸', label: 'United States' },
    { code: '🇺🇾', label: 'Uruguay' },
    { code: '🇺🇿', label: 'Uzbekistan' },
    { code: '🇻🇪', label: 'Venezuela' },
    { code: '🇻🇳', label: 'Vietnam' },
    { code: '🇾🇪', label: 'Yemen' },
    { code: '🇿🇲', label: 'Zambia' },
    { code: '🇿🇼', label: 'Zimbabwe' },
    { code: '🌍', label: 'World' }
];
